version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: earthai_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: earthai_db
      POSTGRES_USER: earthai_user
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 