version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: earthai_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://earthai_user:dev_password_123@db:5432/earthai_db
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: earthai_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: earthai_db
      POSTGRES_USER: earthai_user
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 